<?php

return [
    'iaaas_groups' => [
        'account' => [
            'label' => 'Account',
            'endpoints' => [
                '/v1/aaas/account',
                '/v1/aaas/account/list',
                '/v1/aaas/account/{account_id}',
                '/v1/aaas/account/{account_id}/details',
                '/v1/aaas/account/{account_id}/phone/unlink',
                '/v1/aaas/account/{account_id}/phone',
                '/v1/aaas/account/{account_id}/statement',
                '/v1/aaas/account/{account_id}/balance/lock',
                '/v1/aaas/account/{account_id}/balance/unlock',
                '/v1/aaas/account/{account_id}/payment/refund',
            ],
        ],
        'cashIn' => [
            'label' => 'Cash In',
            'endpoints' => [
                '/v1/aaas/cash-in/{account_id}/pix/static-qr-code',
                '/v1/aaas/cash-in/{account_id}/pix/dynamic-qr-code',
            ],
        ],
        'cashOut' => [
            'label' => 'Cash Out',
            'endpoints' => [
                '/v1/aaas/cash-out/make-pix-transfer',
                '/v1/aaas/cash-out/make-non-priority-pix-transfer',
                '/v1/aaas/cash-out/make-pix-transfer-only-with-alias',
                '/v1/aaas/cash-out/decode-qr-code',
                '/v1/aaas/cash-out/make-bank-transfer',
                '/v1/aaas/cash-out/make-bank-slip-payment',
                '/v1/aaas/cash-out/make-utilities-payment',
                '/v1/aaas/cash-out/make-internal-transfer',
                '/v1/aaas/cash-out/return-internal-transfer',
            ],
        ],
        'transaction' => [
            'label' => 'Transaction',
            'endpoints' => [
                '/v1/aaas/transaction/{transaction_id}',
                '/v1/aaas/transaction/withdraw/{withdraw_id}',
            ],
        ],
        'webhook' => [
            'label' => 'Webhook',
            'endpoints' => [
                '/v1/aaas/webhooks',
                '/v1/aaas/webhooks/list',
                '/v1/aaas/webhooks/{webhook_id}',
                '/v1/aaas/webhooks/{webhook_id}/update',
                '/v1/aaas/webhooks/{webhook_id}/delete',
            ],
        ],
        'batchesAndBillings' => [
            'label' => 'Batches and Billings',
            'endpoints' => [
                '/v1/aaas/process/{file_type}/validate-shipment',
                '/v1/validate/cnab400',
                '/v1/aaas/process/{account_id}/file-type/{file_type}/send-shipment',
                '/v1/aaas/process/{account_id}/send-invoice',
                '/v1/aaas/process/{account_id}/send-recharge',
                '/v1/aaas/process/{account_id}/{payment_slip_number}/get-payment-slip/pdf',
                '/v1/aaas/process/{account_id}/batches/{uuid}/slips/zip',
                '/v1/aaas/process/{account_id}/{payment_slip_number}/get-payment-slip',
                '/v1/aaas/process/{account_id}/batch/{batch_id}/return-file/{format}',
                '/v1/aaas/process/{account_id}/return-file/{format}',
                '/v1/aaas/process/{account_id}/batches',
                '/v1/aaas/process/{account_id}/batches/{uuid}',
                '/v1/aaas/process/{account_id}/billings',
                '/v1/aaas/process/{account_id}/billings/{uuid}',
                '/v1/aaas/process/{account_id}/billings/batch/{batch_uuid}',
                '/v1/aaas/process/{uuid}/status-billing',
                '/v1/aaas/process/{account_id}/billings/{uuid}',
            ],
        ],
    ],
    'ibaas_endpoints' => [
        '/v1/auth/login-webhook',
        '/v1/auth/login',
        '/v1/auth/refresh',
        '/v1/auth/logout',
        '/v1/baas/account/occupations',
        '/v1/baas/account/retrieve-from-provider/by-account-number',
        '/v1/baas/account/retrieve-from-provider/by-account-id',
        '/v1/baas/accounts/migrating/import-csv',
        '/v1/baas/accounts/migrating/search',
        '/v1/baas/accounts/migrating',
        '/v1/baas/accounts/migrating/logs',
        '/v1/baas/accounts/migrating/{uuid}/cancel',
        '/v1/baas/account',
        '/v1/baas/accounts/{account_uuid}',
        '/v1/baas/account/search',
        '/v1/baas/account/{accountId}',
        '/v1/baas/account/by-account-number/{accountBranch}/{accountNumber}',
        '/v1/baas/account/by-tax-id-number/{taxIdNumber}',
        '/v1/baas/account/{account_id}/balance',
        '/v1/baas/account/{account_id}/statement',
        '/v1/baas/account/files/{uuid}/download',
        '/v1/baas/cash-in/{account_id}/pix/static-qr-code',
        '/v1/baas/cash-in/{account_id}/pix/dynamic-qr-code',
        '/v1/baas/cash-in/bank-slip',
        '/v1/baas/cash-in/billing-slip',
        '/v1/baas/cash-in/deposit',
        '/v1/baas/cash-out/{account_id}/pix-transfer',
        '/v1/baas/cash-out/{account_id}/pix-transfer/only-with-alias',
        '/v1/baas/cash-out/pix-transfer/non-priority',
        '/v1/baas/cash-out/{account_id}/bank-transfer',
        '/v1/baas/cash-out/{account_id}/bank-slip-payment',
        '/v1/baas/cash-out/{account_id}/utilities-payment',
        '/v1/baas/cash-out/{account_id}/internal-transfer',
        '/v1/baas/cash-out/internal-transaction/return/{transaction_id}',
        '/v1/baas/transactions/{account_id}/{transaction_id}',
        '/v1/baas/transactions/{account_id}/withdraw/{transaction_id}',
        '/v1/baas/transactions/bank-slip/{bar_code}',
        '/v1/baas/transactions/{account_id}/lock-balance',
        '/v1/baas/transactions/{account_id}/unlock-balance/{lock_id}',
        '/v1/baas/pix/{account_id}/aliases',
        '/v1/baas/pix/{account_id}/aliases/{alias}',
        '/v1/baas/pix/{account_id}/aliases/{alias}/opt-validation',
        '/v1/baas/pix/{account_id}/destination-alias/{country}/{alias}',
        '/v1/baas/pix/{account_id}/aliases/{alias}/portability',
        '/v1/baas/pix/{account_id}/aliases/{alias}/portability/confirmation',
        '/v1/baas/pix/{account_id}/aliases/{alias}/portability/cancellation',
        '/v1/baas/pix/{account_id}/aliases/{alias}/ownership/claims',
        '/v1/baas/pix/{account_id}/aliases/{alias}/ownership/claims/responses',
        '/v1/baas/{account_id}/med/infractions',
        '/v1/baas/{account_id}/med/infractions/{infraction_report_id}/cancel',
        '/v1/baas/{account_id}/med',
        '/v1/baas/{account_id}/med/search',
        '/v1/baas/{account_id}/med/{uuid}',
        '/v1/baas/{account_id}/med/{uuid}/sent',
        '/v1/baas/{account_id}/med/{uuid}/in_analysis',
        '/v1/baas/{account_id}/med/{uuid}/approved',
        '/v1/baas/{account_id}/med/{uuid}/rejected',
        '/v1/baas/{account_id}/med/{uuid}/cancel',
        '/v1/baas/{account_id}/med/situation-types',
        '/v1/baas/{account_id}/med/med-types',
        '/v1/baas/{account_id}/med/med-status',
        '/v1/baas/pix/recurrence/{account_id}',
        '/v1/baas/pix/recurrence/{account_id}/recurrences/{recurrence_id}',
        '/v1/baas/pix/recurrence/{account_id}/authorization',
        '/v1/baas/pix/recurrence/{account_id}/billing/{billing_id}/cancellation',
        '/v1/baas/pix/recurrence/{account_id}/billing',
        '/v1/baas/pix/recurrence/{account_id}/billing/{billing_id}',
        '/v1/baas/pix/{account_id}/get-limits/{limit_type}',
        '/v1/baas/pix/{country}/return-codes',
        '/v1/baas/pix/{country}/psps',
        '/v1/baas/pix/{account_id}/returns/{transaction_id}',
        '/v1/baas/pix/decode-qr-code',
        '/v1/baas/pix/text-to-qr-code',
        '/v1/baas/cellphone-recharge/{country}/area-code/{area-code}/carriers',
        '/v1/baas/cellphone-recharge/{country}/area-code/{area-code}/carriers/{carrier}/values',
        '/v1/baas/cellphone-recharge/{account_id}/recharge',
        '/v1/baas/send-webhook/set-accounts-webhook',
        '/v1/admin/webhooks/search',
        '/v1/baas/limits/{account_id}',
        '/v1/baas/limits/update/request',
        '/v1/baas/limits/update-requests/search',
        '/v1/baas/limits/update/process',
        '/v1/baas/limits/update/request-batch',
        '/v1/baas/limits/update/csv',
        '/v1/baas/charge-report/pdf',
        '/v1/baas/charge-report/search',
        '/v1/baas/{account_id}/payers/search-by',
        '/v1/baas/{account_id}/payers/',
        '/v1/baas/{account_id}/payers/{uuid}',
        '/v1/baas/{account_id}/payers/search',
        '/v1/baas/process/{file_type}/validate-shipment',
        '/v1/baas/process/{account_id}/file-type/{file_type}/send-shipment',
        '/v1/baas/process/{account_id}/send-invoice',
        '/v1/baas/process/{account_id}/send-recharge',
        '/v1/baas/process/{account_id}/batch/{batch_id}/return-file/{format}',
        '/v1/baas/process/{account_id}/start/{start}/end/{end}/return-file/{format}',
        '/v1/baas/process/{account_id}/batches',
        '/v1/baas/process/{account_id}/batch/{uuid}/',
        '/v1/baas/process/{account_id}/billings',
        '/v1/baas/process/{account_id}/billings/{uuid}',
        '/v1/baas/process/{account_id}/billings/{uuid}/regenerate-pdf',
        '/v1/baas/dock/catalog/document-categories',
        '/v1/baas/dock/{plataform}/onboarding/setup-types',
        '/v1/baas/dock/{plataform}/onboarding/product/{productId}/schema-business',
        '/v1/baas/dock/{plataform}/onboarding/product/{product_id}',
        '/v1/baas/dock/{plataform}/onboarding/account/{account_id}',
        '/v1/baas/dock/{plataform}/onboarding/reg-docs',
        '/v1/baas/dock/{plataform}/onboarding/reg-docs/agree/{accountId}',
        '/v1/baas/dock/{plataform}/onboarding/registration/{account_id}/start',
        '/v1/baas/dock/{plataform}/onboarding/registration/{account_id}/file-upload',
        '/v1/baas/dock/{plataform}/onboarding/registration/{account_id}/pending-files',
        '/v1/baas/dock/{plataform}/onboarding/registration/customer-process/{account_id}',
        '/v1/baas/dock/{plataform}/onboarding/registration/proposal/{account_id}',
        '/v1/baas/dock/{plataform}/onboarding/validate/access-token',
        '/v1/baas/dock/{plataform}/onboarding/status/{account_id}',
        '/v1/baas/dock/{plataform}/account/{account_id}',
        '/v1/baas/dock/{plataform}/account/{account_id}/balance',
        '/v1/baas/dock/{plataform}/account/{account_id}/update-status',
        '/v1/baas/dock/{plataform}/account/{account_id}/list-account-entries',
        '/v1/baas/dock/{plataform}/account/{account_id}/limits',
        '/v1/baas/dock/{plataform}/account-manager/{account_id}',
        '/v1/baas/dock/{plataform}/account-manager',
        '/v1/baas/dock/{plataform}/pay/transfer',
        '/v1/baas/dock/{plataform}/pay/transfer/{transfer_id}',
        '/v1/baas/dock/{plataform}/pay/transfer/{account_id}/initiate',
        '/v1/baas/dock/{plataform}/pay/internal-transfer/{account_id}/initiate',
        '/v1/baas/dock/{plataform}/pay/transfer/{transfer_id}/cancel',
        '/v1/baas/dock/{plataform}/pix/dict',
        '/v1/baas/dock/{plataform}/pix/payment',
        '/v1/baas/dock/{plataform}/pix/qr-code/dynamic',
        '/v1/baas/dock/{plataform}/pix/qr-code/static',
        '/v1/baas/dock/{plataform}/pix/dict/validate',
        '/v1/baas/dock/{plataform}/pix/payment/search',
        '/v1/baas/dock/{plataform}/pix/dict/search',
        '/v1/baas/dock/{plataform}/pix/payment/{payment_id}',
        '/v1/baas/dock/{plataform}/pix/fraud-mark',
        '/v1/baas/dock/{plataform}/spending-controls/product-configurations',
        '/v1/baas/dock/{plataform}/spending-controls/groups',
        '/v1/baas/dock/{plataform}/spending-controls/groups-persons',
        '/v1/baas/dock/{plataform}/spending-controls/controls/{id}',
        '/v1/baas/dock/{plataform}/spending-controls/controls',
        '/v1/baas/{account_id}/insurance/sul-america/trip/contract',
        '/v1/baas/{account_id}/insurance/sul-america/trip/policy/consult',
        '/v1/baas/{account_id}/insurance/sul-america/trip/policy/second-copy',
    ],
];
